language: cpp
cache: ccache
matrix:
  include:
    - os: osx
      env: NAME="macos build"
      sudo: false
      osx_image: xcode12
      addons:
        homebrew:
          packages:
          - p7zip 
          - sdl2 
          - ccache 
          - ninja 
          - ffmpeg 
          - pulseaudio
          - mbedtls 
          - gpm 
          - pkgconfig
          - qt 
          - openssl 
          - zstd
          - boost
          - libzip
          - clang-format 
          - gcc@10
          #update: true
      install:
      #- "./.travis/macos/deps.sh"
      - pip3 install macpack
      - pip3 install conan
      script: 
      #- "./.travis/macos/build.sh"
      - git clone --recursive --single-branch -b latest-mac-stuff https://github.com/jroweboy/yuzu.git
      - cd yuzu
      - git submodule update --init --recursive
      - export Qt5_DIR=$(brew --prefix)/opt/qt5
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release
      - make -j4
      after_success: 
      - echo "success"
      #- "./.travis/macos/upload.sh"
deploy:
  provider: script
  script: bash .travis/macos/deploy.sh
  api_key: $GITHUB_TOKEN
#  secure: 
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    branch: mac-git
