language: cpp
cache: ccache
matrix:
  include:
    #- os: linux
     # env: NAME="linux appimage"
     # sudo: required
     # dist: trusty
     # services: docker
     # addons:
     #   apt:
     #     packages:
     #       - p7zip-full
     # install: 
     #  - docker pull quriouspixel/yuzu:latest
     # script: 
     #  - "./.travis/appimage/build.sh"
     # after_success:
     # - ls -al artifacts/
     # - cd artifacts/
     # - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
     # - chmod a+x upload.sh
     # - bash upload.sh yuzu-x86_64.AppImage* 
      #branches:
  #except:
    #- /^(?i:continuous.*)$/
    #- os: linux
    # env: NAME="clang-format"
    #  sudo: required
    #  dist: trusty
    #  services: docker
    #  install: "./.travis/clang-format/deps.sh"
    #  script: "./.travis/clang-format/build.sh"
    #- os: linux
    #  env: NAME="linux build"
    #  sudo: required
    #  dist: trusty
    #  services: docker
    #  addons:
    #    apt:
    #      packages:
    #        - p7zip-full
    #  install: "./.travis/linux/deps.sh"
    #  script: "./.travis/linux/build.sh"
    #  after_success: "./.travis/linux/upload.sh"
    #  cache: ccache
    - os: osx
      env: NAME="macos build"
      sudo: false
      osx_image: xcode10.1
      #install: "./.travis/macos/deps.sh"
      script: 
      - go version
      - wget -c https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
      - tar xfv ghr_v0.13.0_linux_amd64.tar.gz
      - ghr_v0.13.0_linux_amd64/ghr -recreate -n 'Continous build' -b "Travis CI build log ${TRAVIS_BUILD_WEB_URL}" continuous artifacts/
       #after_success: "./.travis/macos/upload.sh"
    #  cache: ccache
    #- os: linux
    #  env: NAME="MinGW build"
    #  sudo: required
    #  dist: trusty
    #  services: docker
    #  addons:
    #    apt:
    #      packages:
    #        - p7zip-full
    #  install: "./.travis/linux-mingw/deps.sh"
    #  script: "./.travis/linux-mingw/build.sh"
    #  after_success: "./.travis/linux-mingw/upload.sh"
    #  cache: ccache

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
#  secure: 
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true

#notifications:
#  webhooks:
#    urls:
#      - https://api.yuzu-emu.org/code/travis/notify
