language: cpp
cache: ccache
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: trusty
      services: docker
      git:
       clone: false
      addons:
        apt:
          packages:
            - p7zip-full
      install: 
       - docker pull quriouspixel/yuzu:latest
      before_script:
       - ls -al /
       - echo $(pwd)
       - ls -al $(pwd)
       #- ls -al yuzu/.travis
       #-
      script: 
       - mkdir -p "$HOME/.ccache"
       - docker run -u root -v $(pwd):/yuzu -v "$HOME/.ccache":/root/.ccache --name yuzu_appimage quriouspixel/yuzu:latest /bin/bash /yuzu/.travis/appimage/docker.sh

     # after_success:
     # - ls -al artifacts/
     # - cd artifacts/
     # - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
     # - chmod a+x upload.sh
     # - bash upload.sh yuzu-x86_64.AppImage* 
      branches:
  except:
   # - /^(?i:continuous.*)$/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
#  secure: 
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true
