language: cpp
cache: ccache
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: trusty
      services: docker
      addons:
        apt:
          packages:
            - p7zip-full
      git:
        clone: true
        submodules: false
      install: 
       - docker pull quriouspixel/yuzu:latest
      script: 
       - mkdir -p "$HOME/.ccache"
       - docker run -u root -e ENABLE_COMPATIBILITY_REPORTING --env-file .travis/common/travis-ci.env -v $(pwd):/yuzu -v "$HOME/.ccache":/root/.ccache --name yuzu_appimage quriouspixel/yuzu:latest /bin/bash /yuzu/.travis/appimage/docker.sh
      after_success:
      - export UPLOADTOOL_SUFFIX=$(date +%Y%m%d)
      - ls -al artifacts/
      - cd artifacts/
      #- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      - wget -c https://raw.githubusercontent.com/qurious-pixel/yuzu/mainline/.travis/appimage/upload.sh
      - chmod a+x upload.sh
      - bash upload.sh yuzu-x86_64.AppImage* 
      branches:
  except:
    - /^(?i:continuous.*)$/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
#  secure: 
  file_glob: true
  file: "artifacts/*"
  overwrite: true
  prerelease: true
  skip_cleanup: true
  on:
    tags: true
