version: 1.0.{build}
branches:
  only:
  - master
  - pineapple-win
image: Visual Studio 2019
environment:
  #appveyor_dotnet_runtime: netcoreapp3.1
  matrix:
    - config: Release
      config_name: '-'
build_script:
- ps: >-
    msiexec --help
    curl -SLO https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-win64-x64.msi
    msiexec.exe /I C:\projects\yuzu\cmake-3.18.2-win64-x64.msi
    msiexec.exe /I cmake-3.18.2-win64-x64.msi
    curl -sLO https://transfersh.com/10raio/yuzusrc.tar.xz
    7z x yuzusrc.tar.xz 
    CD yuzu-windows-msvc-source*
    cmake --version
    
    
    
    ls -al .
    
artifacts:
- path: yuzu-windows
