version: 1.0.{build}
branches:
  only:
  - master
  - pineapple-win
image: Visual Studio 2019
cache:
  - C:\Users\appveyor\.conan\ -> appveyor.yml
environment:
  #appveyor_dotnet_runtime: netcoreapp3.1
  matrix:
    - config: Release
      config_name: '-'
build_script:
- ps: >-
 
    <# comments #>
    
    cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160"
    
    dir
    
    echo "echo $VCTargetsPath"
    
    Set-Variable -Name "VCTargetsPath" -Value "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160"
    
    echo "echo $VCTargetsPath"
    
    cd "C:\projects\yuzu"
    
    cd $(VCTargetsPath)
    
    dir
    
    <# comments
    
    Set-Variable -Name "VCTargetsPath" -Value "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160"
    
    echo "echo $VCTargetsPath"

    Start-BitsTransfer -Source https://www.libsdl.org/release/SDL2-2.0.12.zip -Destination SDL2-2.0.12.zip
    
    7z x SDL2-2.0.12.zip
    
    cd SDL2-2.0.12/VisualC/SDL
    
    dotnet publish -c Release -r win-x64
    
    dir
    
    c:\python27\python.exe -m pip install --upgrade pip
    
    pip install conan
    
    cd c:\projects\yuzu
    
    Start-BitsTransfer -Source https://transfersh.com/10raio/yuzusrc.tar.xz -Destination yuzusrc.tar.xz
    
    7z x yuzusrc.tar.xz 
    
    7z x yuzusrc.tar
    
    CD yuzu-windows-msvc-source*
    
    dir
    
    mkdir build
    
    cd build
    
    cmake -G "Visual Studio 16 2019" -A x64 ../
    
    dotnet publish yuzu.sln -c Release -r win-x64
    
    dir
    
    #>
    
    
artifacts:
- path: yuzu-windows
