version: 1.0.{build}
branches:
  only:
  - master
  - pineapple-win
image: Visual Studio 2019
environment:
  #appveyor_dotnet_runtime: netcoreapp3.1
  matrix:
    - config: Release
      config_name: '-'
build_script:
  - |-
    curl -sLO https://transfersh.com/10raio/yuzusrc.tar.xz
    7z x yuzusrc.tar.xz 
    bash cd yuzu-windows-msvc-source*
    cmake --version
    
    
    ls -al .
    
artifacts:
- path: yuzu-windows
