version: 1.0.{build}
branches:
  only:
  - master
  - pineapple-win
image: Visual Studio 2019
cache:
  - C:\Users\appveyor\.conan\ 
  - C:\Users\appveyor\AppData\Local\vcpkg
  - C:/Tools/vcpkg/packages
  - c:\python27\
environment:
  #appveyor_dotnet_runtime: netcoreapp3.1
  matrix:
    - config: Release
      config_name: '-'
build_script:
- ps: >-
 
    <# comments #>
    
    
    Start-BitsTransfer -Source https://libsdl.org/release/SDL2-devel-2.0.12-VC.zip -Destination SDL2-devel-2.0.12-VC.zip
    
    7z x SDL2-devel-2.0.12-VC.zip
    
    cp "C:\projects\yuzu\externals\sdl2-config.cmake" "C:\projects\yuzu\SDL2-2.0.12\"
    
    $Env:SDL2_DIR = "C:\projects\yuzu\SDL2-2.0.12\"
    
    $SDL2_DIR = $Env:SDL2_DIR
    
    $Env:VCTargetsPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\"
    
    $VCTargetsPath = "$Env:VCTargetsPath"

    vcpkg install --triplet x64-windows sdl2 sdl2-image sdl2-mixer sdl2-net sdl2-ttf
        
    c:\python27\python.exe -m pip install --upgrade pip
    
    pip install conan
    
    cd c:\projects\yuzu
    
    Start-BitsTransfer -Source https://transfersh.com/10raio/yuzusrc.tar.xz -Destination yuzusrc.tar.xz
    
    7z x yuzusrc.tar.xz 
    
    7z x yuzusrc.tar 
    
    CD yuzu-windows-msvc-source*
    
    $env:YUZUSRC = $PWD
    
    echo $env:YUZUSRC
            
    Start-BitsTransfer -Source https://raw.githubusercontent.com/PineappleEA/Pineapple-Linux/master/inject-git-info.patch -Destination inject-git-info.patch

    dos2unix inject-git-info.patch
    
    wsl patch -p1 -i inject-git-info.patch
    
    dir
    
    mkdir build
    
    cd build
            
    cmake -G "Visual Studio 16 2019" -A x64 --config Release -DYUZU_USE_BUNDLED_QT=1 -DYUZU_USE_BUNDLED_UNICORN=1 -DYUZU_USE_QT_WEB_ENGINE=ON -DUSE_DISCORD_PRESENCE=ON -DDISPLAY_VERSION=999 -DTITLE_BAR_FORMAT_IDLE="999" -DTITLE_BAR_FORMAT_RUNNING="999 | {3}" -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON ../
    
    msbuild yuzu.sln /p:Configuration=Release
    
    #cmake -GNinja ../ -DCMAKE_BUILD_TYPE=Release -DUSE_DISCORD_PRESENCE=ON -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON
    
    #ninja
    
    cd $env:YUZUSRC\build\bin\Release
    
    rm *.pdb
    
    dir
    
    cd $env:YUZUSRC\build\bin\
    
    7z a yuzu-release.zip "Release"
    
    mv yuzu-release.zip c:\projects\yuzu
    
    #>
    
artifacts:
- path: yuzu-release.zip
