version: 1.0.{build}
branches:
  only:
  - master
  - pineapple-win
image: Visual Studio 2019
environment:
  #appveyor_dotnet_runtime: netcoreapp3.1
  matrix:
    - config: Release
      config_name: '-'
build_script:
- ps: >-
    
    -bash: curl -sLO 
    Start-BitsTransfer -Source https://transfersh.com/10raio/yuzusrc.tar.xz -Destination yuzusrc.tar.xz
    
    7z x yuzusrc.tar.xz 
    
    CD yuzu-windows-msvc-source*
    
    dir
    
artifacts:
- path: yuzu-windows
