version: 1.0.{build}
branches:
  only:
  - master
  - pineapple-win
image: Visual Studio 2019
cache:
  - C:\Users\appveyor\.conan\ 
  - C:\Users\appveyor\AppData\Local\vcpkg
  - C:/Tools/vcpkg/packages
  - c:\python27\
environment:
  #appveyor_dotnet_runtime: netcoreapp3.1
  matrix:
    - config: Release
      config_name: '-'
build_script:
- ps: >-
 
    <# comments #>
    
    
    $Env:VCTargetsPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\"
    
    $VCTargetsPath = "$Env:VCTargetsPath"

    #vcpkg install --triplet x64-windows sdl2 sdl2-image sdl2-mixer sdl2-net sdl2-ttf
        
    c:\python27\python.exe -m pip install --upgrade pip
    
    pip install conan
    
    cd c:\projects\yuzu
    
    Start-BitsTransfer -Source https://transfersh.com/10raio/yuzusrc.tar.xz -Destination yuzusrc.tar.xz
    
    7z x yuzusrc.tar.xz 
    
    7z x yuzusrc.tar
    
    CD yuzu-windows-msvc-source*
    
    dir
    
    mkdir build
    
    cd build
    
    cmake -G "Visual Studio 16 2019" -A x64 ../ -DCMAKE_BUILD_TYPE=Release -DUSE_DISCORD_PRESENCE=ON -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON
    
    msbuild yuzu.sln 
    
    #cmake -GNinja ../ -DCMAKE_BUILD_TYPE=Release -DUSE_DISCORD_PRESENCE=ON -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON
    
    #ninja
    
    dir
    
    cd bin
    
    dir
    
    cd ..\x64
    
    dir
    
    #>
    
artifacts:
- path: bin\yuzu.exe
