version: 1.0.{build}
branches:
  only:
  - master
  - pineapple-win
image: Visual Studio 2019
environment:
  #appveyor_dotnet_runtime: netcoreapp3.1
  matrix:
    - config: Release
      config_name: '-'
build_script:
- ps: >-
 
    <# comments
    
    Start-BitsTransfer -Source https://www.libsdl.org/release/SDL2-2.0.12.zip -Destination SDL2-2.0.12.zip
    
    Start-BitsTransfer -Source https://transfersh.com/10raio/yuzusrc.tar.xz -Destination yuzusrc.tar.xz
    
    7z x yuzusrc.tar.xz 
    
    7z x yuzusrc.tar
    
    CD yuzu-windows-msvc-source*
    
    dir
    
    mkdir build
    
    cd build
    
    cmake -G "Visual Studio 16 2019" -A x64 ../
    
    #> comments
    
    pip install conan
    
    dir
    
artifacts:
- path: yuzu-windows
