version: 1.0.{build}
branches:
  only:
  - master
  - pineapple-win
image: Visual Studio 2019
environment:
  appveyor_dotnet_runtime: netcoreapp3.1
  matrix:
    - config: Release
      config_name: '-'
build_script:
- bash: >-
    curl -s https://raw.githubusercontent.com/pineappleEA/pineappleEA.github.io/master/index.html > sourcefile.txt
    latest=$(cat sourcefile.txt | grep https://anonfiles.com/ | cut -d '=' -f 2 | cut -d '>' -f 1 | head -n 1)
    title=$(echo $latest | cut -d '/' -f 5 | head -n 1 | cut -d '_' -f 1)
    curl -sLO $(curl $latest | grep -o 'https://cdn-.*.7z' | head -n 1)
    7z x Yuzu* yuzu-windows-msvc-early-access/yuzu-windows-msvc-source-*
    cd yuzu-windows-msvc-early-access
    msvc=$(grep yuzu-windows-msvc-source | cut -d '-' -f 5 | cut -d '.' -f 1 )
    tar -xf yuzu-windows-msvc-source-* --directory .
    
    ls -al .
    
artifacts:
- path: yuzu-windows
